ALTER TABLE public.cards
  ADD COLUMN IF NOT EXISTS bouquet TEXT NOT NULL DEFAULT 'rose',
  ADD COLUMN IF NOT EXISTS opener TEXT NOT NULL DEFAULT 'envelope',
  ADD COLUMN IF NOT EXISTS song_url TEXT;
ALTER TABLE public.cards ALTER COLUMN flowers DROP NOT NULL;